USE [master]
GO

/****** Object:  Database [Furnishing_Store]    Script Date: 2/28/2021 1:54:17 PM ******/
CREATE DATABASE [Furnishing_Store]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Furnishing_Store', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Furnishing_Store.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Furnishing_Store_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Furnishing_Store_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Furnishing_Store].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Furnishing_Store] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Furnishing_Store] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Furnishing_Store] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Furnishing_Store] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Furnishing_Store] SET ARITHABORT OFF 
GO

ALTER DATABASE [Furnishing_Store] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Furnishing_Store] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Furnishing_Store] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Furnishing_Store] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Furnishing_Store] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Furnishing_Store] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Furnishing_Store] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Furnishing_Store] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Furnishing_Store] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Furnishing_Store] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Furnishing_Store] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Furnishing_Store] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Furnishing_Store] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Furnishing_Store] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Furnishing_Store] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Furnishing_Store] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Furnishing_Store] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Furnishing_Store] SET RECOVERY FULL 
GO

ALTER DATABASE [Furnishing_Store] SET  MULTI_USER 
GO

ALTER DATABASE [Furnishing_Store] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Furnishing_Store] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Furnishing_Store] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Furnishing_Store] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Furnishing_Store] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Furnishing_Store] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Furnishing_Store] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Furnishing_Store] SET  READ_WRITE 
GO


